// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserList.Api.Models;

namespace UserList.Api.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20191124175038_Seed2")]
    partial class Seed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("UserList.Api.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "FBloggs99",
                            FamilyName = "Bloggs",
                            FirstName = "Fred"
                        },
                        new
                        {
                            Username = "BSmith",
                            FamilyName = "Smith",
                            FirstName = "Bob"
                        },
                        new
                        {
                            Username = "Billy99",
                            FamilyName = "Smith",
                            FirstName = "Billy"
                        },
                        new
                        {
                            Username = "Prince",
                            FamilyName = "Prince"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
